import {
  ShowcaseCard,
  ProjectCategory,
} from "@/app/showcase/lib/showcaseInterface";

// Corrected showcase data
export const showcaseData: ShowcaseCard[] = [
  {
    id: "1",
    projectName: "Portfolio Pro",
    headline: "A sleek and modern portfolio builder",
    creator: {
      userId: "u1",
      username: "Alex Doe",
      email: "alex@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Software,
    tags: ["React", "Tailwind CSS", "JavaScript"],
    builtUsing: ["React", "Tailwind CSS", "Firebase"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/portfolio-pro",
    views: 1200,
    upvotesCount: 300,
    bookmarksCount: 150,
    commentsCount: 25,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    projectName: "Manga Hub",
    headline: "The ultimate manga collection platform",
    creator: {
      userId: "u2",
      username: "Jane Smith",
      email: "jane@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Content,
    tags: ["Manga", "Japanese Culture"],
    builtUsing: ["Node.js", "MongoDB"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/manga-hub",
    views: 800,
    upvotesCount: 250,
    bookmarksCount: 120,
    commentsCount: 18,
    featured: false,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    projectName: "Streetwear Collection 2024",
    headline: "Trendy streetwear designs for urban youth",
    creator: {
      userId: "u3",
      username: "Chris Lee",
      email: "chris@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Design,
    tags: ["Streetwear", "Fashion", "Trendy"],
    builtUsing: ["Illustrator", "Photoshop"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/streetwear-collection",
    views: 650,
    upvotesCount: 200,
    bookmarksCount: 80,
    commentsCount: 10,
    featured: false,
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "4",
    projectName: "Acoustic Vibes",
    headline: "A collection of soothing acoustic guitar tracks",
    creator: {
      userId: "u4",
      username: "Sam Thompson",
      email: "sam@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Art,
    tags: ["Guitar", "Acoustic", "Relaxing"],
    builtUsing: ["GarageBand", "Logic Pro"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/acoustic-vibes",
    views: 950,
    upvotesCount: 400,
    bookmarksCount: 220,
    commentsCount: 35,
    featured: true,
    createdAt: new Date("2024-04-12"),
  },
  {
    id: "5",
    projectName: "Business Accelerator Workshop",
    headline: "A hands-on business workshop for startups",
    creator: {
      userId: "u5",
      username: "Mia White",
      email: "mia@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Marketing,
    tags: ["Startups", "Entrepreneurship"],
    builtUsing: ["Google Slides", "Zoom"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/business-accelerator",
    views: 700,
    upvotesCount: 280,
    bookmarksCount: 95,
    commentsCount: 22,
    featured: false,
    createdAt: new Date("2024-05-01"),
  },
  {
    id: "6",
    projectName: "The Painted Canvas",
    headline: "A curated collection of modern abstract art",
    creator: {
      userId: "u6",
      username: "Olivia Brown",
      email: "olivia@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Design,
    tags: ["Abstract Art", "Painting", "Creativity"],
    builtUsing: ["Acrylic", "Canvas"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/the-painted-canvas",
    views: 1250,
    upvotesCount: 500,
    bookmarksCount: 300,
    commentsCount: 45,
    featured: true,
    createdAt: new Date("2024-06-15"),
  },
  {
    id: "7",
    projectName: "Sustainable Farming Initiative",
    headline: "Promoting eco-friendly farming techniques",
    creator: {
      userId: "u7",
      username: "Liam Davis",
      email: "liam@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Community,
    tags: ["Sustainability", "Eco-friendly", "Farming"],
    builtUsing: ["Hydroponics", "Permaculture"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/sustainable-farming",
    views: 980,
    upvotesCount: 330,
    bookmarksCount: 175,
    commentsCount: 28,
    featured: false,
    createdAt: new Date("2024-07-22"),
  },
  {
    id: "8",
    projectName: "Bangalore Startup Conference",
    headline: "Annual startup conference for entrepreneurs in Bangalore",
    creator: {
      userId: "u8",
      username: "Nina Patel",
      email: "nina@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Community,
    tags: ["Startup", "Conference", "Entrepreneurship"],
    builtUsing: ["Eventbrite", "Slack"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/bangalore-startup-conference",
    views: 700,
    upvotesCount: 220,
    bookmarksCount: 95,
    commentsCount: 15,
    featured: false,
    createdAt: new Date("2024-08-05"),
  },
  {
    id: "9",
    projectName: "Indie Short Film Festival",
    headline: "A showcase of short films from indie filmmakers",
    creator: {
      userId: "u9",
      username: "Oscar Garcia",
      email: "oscar@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Community,
    tags: ["Short Film", "Indie", "Filmmaking"],
    builtUsing: ["Premiere Pro", "After Effects"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/indie-short-film-festival",
    views: 1300,
    upvotesCount: 600,
    bookmarksCount: 320,
    commentsCount: 50,
    featured: true,
    createdAt: new Date("2024-09-15"),
  },
  {
    id: "10",
    projectName: "Fitness App UI Design",
    headline: "A clean and user-friendly UI design for a fitness app",
    creator: {
      userId: "u10",
      username: "Emma Wilson",
      email: "emma@example.com",
      imageUrl: "placeholder.png",
    },
    categorie: ProjectCategory.Design,
    tags: ["UI/UX", "Figma", "Design"],
    builtUsing: ["Figma", "Adobe XD"],
    coverImage: "placeholder.png",
    projectUrl: "https://sandbox23.com/fitness-app-design",
    views: 850,
    upvotesCount: 300,
    bookmarksCount: 140,
    commentsCount: 25,
    featured: false,
    createdAt: new Date("2024-10-10"),
  },
];
